# Generated by Django 4.2.7 on 2023-11-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='datecompleted',
            field=models.DateTimeField(null=True),
        ),
    ]
