# Generated by Django 4.2.7 on 2023-11-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_notas_datecompleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='nota',
            field=models.FloatField(default=False),
        ),
    ]
