# Generated by Django 4.2.7 on 2023-11-20 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_notas_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notas',
            name='nota',
        ),
    ]
