# Generated by Django 4.2.7 on 2023-11-20 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_notas_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='notas',
            name='nota',
            field=models.FloatField(default=0.0),
        ),
    ]
