# Generated by Django 4.2.7 on 2023-12-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_notas_nota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notas',
            name='nota',
            field=models.CharField(max_length=200),
        ),
    ]
